### ISSUE TITLE
Error running timer `org-pomodoro-tick': (void-variable org-pomodoro-finish-sound-p) 

### ISSUE THREAD

**Issue by malcolmsparks** [lolownia/org-pomodoro#55] opened 2016-03-25 13:14 UTC
With 2.0.3, At the end of the pomodoro, I'm getting the following error

```
Error running timer `org-pomodoro-tick': (void-variable org-pomodoro-finish-sound-p) 
```

Emacs 24.5.1 on Linux

**Comment by leoc** [comment] 2016-04-01 10:54
Hi @malcolmsparks 

I cannot find any reference for `org-pomodoro-finish-sound-p` in any source file, could it be that you have some hooks defined somewhere that might cause the error?

Otherwise, could you use `toggle-debug-on-error` and show me the trace, please?

Cheers!

**Comment by mcshicks** [comment] 2016-04-04 22:50
I saw the same problem and it went away when I installed from melpa instead of melpa stable

**Comment by ldf-** [comment] 2016-05-04 18:19
The problem is in version 2.0.3

In line 326: `org-pomodoro-finish-sound-p'
It should be `org-pomodoro-finish**ed**-sound-p' instead

This is fixed in the latest master. Melpa stable is still serving version 2.0.3 though.

**Comment by leoc** [comment] 2016-07-25 10:30
MELPA stable serves 2.0.3 now. This should be fixed

**Closed by leoc** 2016-07-25 10:30 UTC
