### ISSUE TITLE
Ticking sound freezes OS X

### ISSUE THREAD

**Issue by gabrielalmeida** [lolownia/org-pomodoro#43] opened 2015-08-13 03:45 UTC
On OS X 10.11 with ```railwaycat/emacs-mac``` port from brew, the following settings:

```elisp
  (setq org-pomodoro-audio-player "mplayer")
  (setq org-pomodoro-ticking-sound-args "-volume 3")
  (setq org-pomodoro-ticking-sound-p t)
```
Results in processes running simultaneously and increasing by number over time:
<img width="1920" alt="screenshot 2015-08-13 00 10 29" src="https://cloud.githubusercontent.com/assets/310382/9242127/4f0a585a-4153-11e5-99c7-fb1b59f06991.png">

Everything starts to slow down and then freezes. The same happens when using default ```afplay```.

Thanks for this great package!

**Comment by leoc** [comment] 2016-04-01 11:07
Hi @gabrielalmeida 

Do you still have this problem? I cannot reproduce this issue. 
How do you integrate `org-pomodoro` into your emacs setup (full code for package installation, version of org-pomodoro)?

Cheers!

**Comment by gabrielalmeida** [comment] 2016-04-01 14:27
Hi @leoc 

I'm no longer using `org-pomodoro` nowadays, when I've encountered this issue I was using it with [syl20bnr/spacemacs](https://github.com/syl20bnr/spacemacs), which handled `org` setup itself.

Cheers

**Comment by leoc** [comment] 2016-04-01 16:46
Alright, thanks. Sorry for the delay. I close this issue for now.

**Closed by leoc** 2016-04-01 16:46 UTC
