### ISSUE TITLE
Error running timer ‘org-pomodoro-tick’: (error "‘recenter’ing a window that does not display current-buffer.")

### ISSUE THREAD

**Issue by Carter-Pro** [lolownia/org-pomodoro#56] opened 2016-05-05 15:25 UTC
Some times I will get this information, and when this info comes up where will be two problems:

1. the sound of pomodoro did not work
2. the function like `org-pomodoro-finished-hook`/`org-pomodoro-break-hook` did not work

I test many times, and I can not figure out how this comes.

**Comment by marsam** [comment] 2016-07-04 18:36
Steps to reproduce this issue:

1. Call `org-agenda`, the `*Org Agenda*` buffer should be a existing live buffer
2. Start and stop a pomodoro with `org-pomodoro`

Hi @Carter-Pro I've made a fix for this in #59, could you please try it

**Comment by zilongshanren** [comment] 2016-07-20 02:46
+1 for this issue, it's very annoying...

**Comment by sxdxyxy** [comment] 2016-07-23 07:21
+1 for this issue, and have not yet get fixed.

**Comment by leoc** [comment] 2016-07-25 10:28
Since I cannot reproduce this bug, did anyone check out @marsam s fix above?
Does it fix the problem of this issue?

**Closed** 2016-07-25 10:32 UTC

**Comment by leoc** [comment] 2016-07-25 10:52
I pushed a new version with the fix mentioned above. Please reopen, if the issue persists. Thank you!
